on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    # Remove the 'paths:' section to scan on all pushes, not just workflow changes
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 26 17 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Add security-events permission for SARIF upload
      security-events: write
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci
